#!/bin/sh

echo "🔍 Running detekt, ktlint and lint checks..."

./gradlew lint detektCheck ktlintCheck
status=$?

if [ $status -ne 0 ]; then
  echo "❌ Check failed. Push aborted."
  exit 1
fi

echo "✅ All checks passed. Proceeding with push."
exit 0
