#!/bin/bash

#
# Copyright 2023 Sertan Canpolat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# Run Detekt
echo "Running Detekt..."
./gradlew detektCheck
detektStatus=$?

# Run Ktlint
echo "Running Ktlint..."
./gradlew ktlintCheck
ktlintStatus=$?

# Check both statuses
if [ "$detektStatus" -eq 0 ] && [ "$ktlintStatus" -eq 0 ]; then
    echo "Static analysis found no problems."
    # Add the staged files back to the staging area
    for file in $stagedFiles; do
        if [ -f "$file" ]; then
            git add "$file"
        fi
    done
    exit 0
else
    echo "*********************************************************"
    if [ "$detektStatus" -ne 0 ]; then
        echo >&2 "Detekt found violations."
    fi
    if [ "$ktlintStatus" -ne 0 ]; then
        echo >&2 "Ktlint found violations."
        echo "> Try ./gradlew ktlintFormat"
    fi
    echo "See 'reports' folder for more detail."
    echo "*********************************************************"
    exit 1
fi
