name: Lint, Detekt and Ktlint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Scan with Ktlint
        run: ./gradlew ktlintCheck

      - name: Scan with Detekt
        run: ./gradlew detektCheck

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**